import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import eslintConfigPrettier from "eslint-config-prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

// eslint-config-next doesn't ship a native flat config yet, hence
// FlatCompat translating its legacy .eslintrc-shaped export — this is
// the same pattern `create-next-app` itself generates for Next 15 + ESLint 9.
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is regenerated by Next.js itself on every build/dev
    // run — its triple-slash reference is required by Next's own tooling,
    // not something to "fix" in a file this project never hand-edits.
    ignores: [".next/**", "node_modules/**", "supabase/.temp/**", "coverage/**", "next-env.d.ts"],
  },
  {
    rules: {
      // CLAUDE.md rule 6: no `any`. next/typescript's default is `warn`;
      // this stage's brief is to make quality gates actually gate.
      "@typescript-eslint/no-explicit-any": "error",
      // CLAUDE.md rule 6 again: a non-null assertion is allowed only with
      // an inline comment explaining why — this rule can't read comments,
      // but banning bare `!` outright is the closest enforceable proxy,
      // and every existing use in this codebase already carries one.
      "@typescript-eslint/no-non-null-assertion": "error",
      // Matches the underscore-prefix convention already used across the
      // app's Server Actions (e.g. `_prevState` in useActionState
      // reducers) — an unused var/arg named `_foo` is a deliberate
      // "required by the signature, not needed here" marker, not dead code.
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  // Disables every ESLint rule that only exists to enforce formatting
  // Prettier already owns — must stay last so nothing after it
  // re-enables one of those rules.
  eslintConfigPrettier,
];

export default eslintConfig;
